spring.application.name=Procedimentos
server.port=6969
# 1. A URL de conexão, apontando para o banco que você criou no Passo 1
spring.datasource.url=jdbc:mysql://localhost:3306/podologia

# 2. Suas credenciais. O usuário padrão é 'root'.
# A senha é aquela que você definiu para o 'root' quando instalou o MySQL.
spring.datasource.username=root
spring.datasource.password=root

# 3. Configuração do Hibernate para criar as tabelas com base no seu código
spring.jpa.hibernate.ddl-auto=create

# 4. (Opcional, mas útil) Para ver os comandos SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true